name: Collector
on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and run Golang file
      run: |
        go run ./main.go
    
    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./vmess_iran.txt
        git add ./trojan_iran.txt
        git add ./vless_iran.txt
        git add ./ss_iran.txt
        git add ./mixed_iran.txt
        git checkout main
        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
