name: Speed Test

on:
  push:
    paths:
      - "./EternityBase"
      - "./sub/sub_merge_base64.txt"
      - "./sub/sub_merge_yaml.yml"

jobs:
  main:
    name: SpeedTest & Filter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'

      - name: Install Requirements
        run: |
          pip install -r ./utils/requirements.txt

      - name: Running Collector
        run: |
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          node ./utils/localserver/index.js &
          sleep 2
          python ./utils/list_merge.py
          
      - name: Run Lite Speedtest
        run: |
          sleep 5
          sudo sh ./utils/speedtest/speedtest2_yaml.sh
          python ./utils/speedtest/output.py
          
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add ./sub
          git add ./utils/Country.mmdb
          git add README.md
          git checkout master
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected & Tested"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: master

      - name: Run Convertor & Formatter
        run: |
          sleep 5
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          python ./utils/eternity_convert.py
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add Eternity.yml
          git add README.md
          git add ./update/*
          git checkout master
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Filtered & Tested"

      - name: Push Change
        uses: ad-m/github-push-action@master
        with:
          branch: master
